/*
 * Copyright (C) 2026 Orange Pi 5B image builders
 *
 * SPDX-License-Identifier: MIT
 *
 * GENERATED by tools/gen-sync.py -- do not edit by hand.
 */


#ifndef _SYNC_H_
#define _SYNC_H_

#include <va/va_backend.h>

VAStatus SyncAcquireBufferHandle(VADriverContextP context, VABufferID buffer_id, VABufferInfo *buffer_info);
VAStatus SyncAssociateSubpicture(VADriverContextP context, VASubpictureID subpicture_id, VASurfaceID *surfaces_ids, int surfaces_count, short src_x, short src_y, unsigned short src_width, unsigned short src_height, short dst_x, short dst_y, unsigned short dst_width, unsigned short dst_height, unsigned int flags);
VAStatus SyncBeginPicture(VADriverContextP context, VAContextID context_id, VASurfaceID surface_id);
VAStatus SyncBufferInfo(VADriverContextP context, VABufferID buffer_id, VABufferType *type, unsigned int *size, unsigned int *count);
VAStatus SyncBufferSetNumElements(VADriverContextP context, VABufferID buffer_id, unsigned int count);
VAStatus SyncCreateBuffer(VADriverContextP context, VAContextID context_id, VABufferType type, unsigned int size, unsigned int count, void *data, VABufferID *buffer_id);
VAStatus SyncCreateConfig(VADriverContextP context, VAProfile profile, VAEntrypoint entrypoint, VAConfigAttrib *attributes, int attributes_count, VAConfigID *config_id);
VAStatus SyncCreateContext(VADriverContextP context, VAConfigID config_id, int picture_width, int picture_height, int flags, VASurfaceID *surfaces_ids, int surfaces_count, VAContextID *context_id);
VAStatus SyncCreateImage(VADriverContextP context, VAImageFormat *format, int width, int height, VAImage *image);
VAStatus SyncCreateSubpicture(VADriverContextP context, VAImageID image_id, VASubpictureID *subpicture_id);
VAStatus SyncCreateSurfaces(VADriverContextP context, int width, int height, int format, int surfaces_count, VASurfaceID *surfaces_ids);
VAStatus SyncCreateSurfaces2(VADriverContextP context, unsigned int format, unsigned int width, unsigned int height, VASurfaceID *surfaces_ids, unsigned int surfaces_count, VASurfaceAttrib *attributes, unsigned int attributes_count);
VAStatus SyncDeassociateSubpicture(VADriverContextP context, VASubpictureID subpicture_id, VASurfaceID *surfaces_ids, int surfaces_count);
VAStatus SyncDeriveImage(VADriverContextP context, VASurfaceID surface_id, VAImage *image);
VAStatus SyncDestroyBuffer(VADriverContextP context, VABufferID buffer_id);
VAStatus SyncDestroyConfig(VADriverContextP context, VAConfigID config_id);
VAStatus SyncDestroyContext(VADriverContextP context, VAContextID context_id);
VAStatus SyncDestroyImage(VADriverContextP context, VAImageID image_id);
VAStatus SyncDestroySubpicture(VADriverContextP context, VASubpictureID subpicture_id);
VAStatus SyncDestroySurfaces(VADriverContextP context, VASurfaceID *surfaces_ids, int surfaces_count);
VAStatus SyncEndPicture(VADriverContextP context, VAContextID context_id);
VAStatus SyncExportSurfaceHandle(VADriverContextP context, VASurfaceID surface_id, uint32_t mem_type, uint32_t flags, void *descriptor);
VAStatus SyncGetConfigAttributes(VADriverContextP context, VAProfile profile, VAEntrypoint entrypoint, VAConfigAttrib *attributes, int attributes_count);
VAStatus SyncGetDisplayAttributes(VADriverContextP context, VADisplayAttribute *attributes, int attributes_count);
VAStatus SyncGetImage(VADriverContextP context, VASurfaceID surface_id, int x, int y, unsigned int width, unsigned int height, VAImageID image_id);
VAStatus SyncLockSurface(VADriverContextP context, VASurfaceID surface_id, unsigned int *fourcc, unsigned int *luma_stride, unsigned int *chroma_u_stride, unsigned int *chroma_v_stride, unsigned int *luma_offset, unsigned int *chroma_u_offset, unsigned int *chroma_v_offset, unsigned int *buffer_name, void **buffer);
VAStatus SyncMapBuffer(VADriverContextP context, VABufferID buffer_id, void **data_map);
VAStatus SyncPutImage(VADriverContextP context, VASurfaceID surface_id, VAImageID image, int src_x, int src_y, unsigned int src_width, unsigned int src_height, int dst_x, int dst_y, unsigned int dst_width, unsigned int dst_height);
VAStatus SyncPutSurface(VADriverContextP context, VASurfaceID surface_id, void *draw, short src_x, short src_y, unsigned short src_width, unsigned short src_height, short dst_x, short dst_y, unsigned short dst_width, unsigned short dst_height, VARectangle *cliprects, unsigned int cliprects_count, unsigned int flags);
VAStatus SyncQueryConfigAttributes(VADriverContextP context, VAConfigID config_id, VAProfile *profile, VAEntrypoint *entrypoint, VAConfigAttrib *attributes, int *attributes_count);
VAStatus SyncQueryConfigEntrypoints(VADriverContextP context, VAProfile profile, VAEntrypoint *entrypoints, int *entrypoints_count);
VAStatus SyncQueryConfigProfiles(VADriverContextP context, VAProfile *profiles, int *profiles_count);
VAStatus SyncQueryDisplayAttributes(VADriverContextP context, VADisplayAttribute *attributes, int *attributes_count);
VAStatus SyncQueryImageFormats(VADriverContextP context, VAImageFormat *formats, int *formats_count);
VAStatus SyncQuerySubpictureFormats(VADriverContextP context, VAImageFormat *formats, unsigned int *flags, unsigned int *formats_count);
VAStatus SyncQuerySurfaceAttributes(VADriverContextP context, VAConfigID config, VASurfaceAttrib *attributes, unsigned int *attributes_count);
VAStatus SyncQuerySurfaceStatus(VADriverContextP context, VASurfaceID surface_id, VASurfaceStatus *status);
VAStatus SyncReleaseBufferHandle(VADriverContextP context, VABufferID buffer_id);
VAStatus SyncRenderPicture(VADriverContextP context, VAContextID context_id, VABufferID *buffers, int buffers_count);
VAStatus SyncSetDisplayAttributes(VADriverContextP context, VADisplayAttribute *attributes, int attributes_count);
VAStatus SyncSetImagePalette(VADriverContextP context, VAImageID image_id, unsigned char *palette);
VAStatus SyncSetSubpictureChromakey(VADriverContextP context, VASubpictureID subpicture_id, unsigned int chromakey_min, unsigned int chromakey_max, unsigned int chromakey_mask);
VAStatus SyncSetSubpictureGlobalAlpha(VADriverContextP context, VASubpictureID subpicture_id, float global_alpha);
VAStatus SyncSetSubpictureImage(VADriverContextP context, VASubpictureID subpicture_id, VAImageID image_id);
VAStatus SyncSyncSurface(VADriverContextP context, VASurfaceID surface_id);
VAStatus SyncUnlockSurface(VADriverContextP context, VASurfaceID surface_id);
VAStatus SyncUnmapBuffer(VADriverContextP context, VABufferID buffer_id);

#endif