/*
 * Copyright (C) 2026 Orange Pi 5B image builders
 *
 * SPDX-License-Identifier: MIT
 *
 * GENERATED by tools/gen-sync.py -- do not edit by hand.
 */


/*
 * RequestSyncSurface is the one that matters for throughput: it releases the
 * lock across the wait for the hardware, which is nearly all of a decode's
 * wall time. What is serialised here is bookkeeping, not decoding.
 */

#include <pthread.h>

#include <va/va_backend.h>

#include "buffer.h"
#include "config.h"
#include "context.h"
#include "image.h"
#include "picture.h"
#include "request.h"
#include "subpicture.h"
#include "surface.h"
#include "sync.h"

VAStatus SyncAcquireBufferHandle(VADriverContextP context, VABufferID buffer_id, VABufferInfo *buffer_info)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestAcquireBufferHandle(context, buffer_id, buffer_info);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncAssociateSubpicture(VADriverContextP context, VASubpictureID subpicture_id, VASurfaceID *surfaces_ids, int surfaces_count, short src_x, short src_y, unsigned short src_width, unsigned short src_height, short dst_x, short dst_y, unsigned short dst_width, unsigned short dst_height, unsigned int flags)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestAssociateSubpicture(context, subpicture_id, surfaces_ids, surfaces_count, src_x, src_y, src_width, src_height, dst_x, dst_y, dst_width, dst_height, flags);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncBeginPicture(VADriverContextP context, VAContextID context_id, VASurfaceID surface_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestBeginPicture(context, context_id, surface_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncBufferInfo(VADriverContextP context, VABufferID buffer_id, VABufferType *type, unsigned int *size, unsigned int *count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestBufferInfo(context, buffer_id, type, size, count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncBufferSetNumElements(VADriverContextP context, VABufferID buffer_id, unsigned int count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestBufferSetNumElements(context, buffer_id, count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncCreateBuffer(VADriverContextP context, VAContextID context_id, VABufferType type, unsigned int size, unsigned int count, void *data, VABufferID *buffer_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestCreateBuffer(context, context_id, type, size, count, data, buffer_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncCreateConfig(VADriverContextP context, VAProfile profile, VAEntrypoint entrypoint, VAConfigAttrib *attributes, int attributes_count, VAConfigID *config_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestCreateConfig(context, profile, entrypoint, attributes, attributes_count, config_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncCreateContext(VADriverContextP context, VAConfigID config_id, int picture_width, int picture_height, int flags, VASurfaceID *surfaces_ids, int surfaces_count, VAContextID *context_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestCreateContext(context, config_id, picture_width, picture_height, flags, surfaces_ids, surfaces_count, context_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncCreateImage(VADriverContextP context, VAImageFormat *format, int width, int height, VAImage *image)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestCreateImage(context, format, width, height, image);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncCreateSubpicture(VADriverContextP context, VAImageID image_id, VASubpictureID *subpicture_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestCreateSubpicture(context, image_id, subpicture_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncCreateSurfaces(VADriverContextP context, int width, int height, int format, int surfaces_count, VASurfaceID *surfaces_ids)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestCreateSurfaces(context, width, height, format, surfaces_count, surfaces_ids);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncCreateSurfaces2(VADriverContextP context, unsigned int format, unsigned int width, unsigned int height, VASurfaceID *surfaces_ids, unsigned int surfaces_count, VASurfaceAttrib *attributes, unsigned int attributes_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestCreateSurfaces2(context, format, width, height, surfaces_ids, surfaces_count, attributes, attributes_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncDeassociateSubpicture(VADriverContextP context, VASubpictureID subpicture_id, VASurfaceID *surfaces_ids, int surfaces_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestDeassociateSubpicture(context, subpicture_id, surfaces_ids, surfaces_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncDeriveImage(VADriverContextP context, VASurfaceID surface_id, VAImage *image)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestDeriveImage(context, surface_id, image);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncDestroyBuffer(VADriverContextP context, VABufferID buffer_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestDestroyBuffer(context, buffer_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncDestroyConfig(VADriverContextP context, VAConfigID config_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestDestroyConfig(context, config_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncDestroyContext(VADriverContextP context, VAContextID context_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestDestroyContext(context, context_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncDestroyImage(VADriverContextP context, VAImageID image_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestDestroyImage(context, image_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncDestroySubpicture(VADriverContextP context, VASubpictureID subpicture_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestDestroySubpicture(context, subpicture_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncDestroySurfaces(VADriverContextP context, VASurfaceID *surfaces_ids, int surfaces_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestDestroySurfaces(context, surfaces_ids, surfaces_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncEndPicture(VADriverContextP context, VAContextID context_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestEndPicture(context, context_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncExportSurfaceHandle(VADriverContextP context, VASurfaceID surface_id, uint32_t mem_type, uint32_t flags, void *descriptor)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestExportSurfaceHandle(context, surface_id, mem_type, flags, descriptor);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncGetConfigAttributes(VADriverContextP context, VAProfile profile, VAEntrypoint entrypoint, VAConfigAttrib *attributes, int attributes_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestGetConfigAttributes(context, profile, entrypoint, attributes, attributes_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncGetDisplayAttributes(VADriverContextP context, VADisplayAttribute *attributes, int attributes_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestGetDisplayAttributes(context, attributes, attributes_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncGetImage(VADriverContextP context, VASurfaceID surface_id, int x, int y, unsigned int width, unsigned int height, VAImageID image_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestGetImage(context, surface_id, x, y, width, height, image_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncLockSurface(VADriverContextP context, VASurfaceID surface_id, unsigned int *fourcc, unsigned int *luma_stride, unsigned int *chroma_u_stride, unsigned int *chroma_v_stride, unsigned int *luma_offset, unsigned int *chroma_u_offset, unsigned int *chroma_v_offset, unsigned int *buffer_name, void **buffer)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestLockSurface(context, surface_id, fourcc, luma_stride, chroma_u_stride, chroma_v_stride, luma_offset, chroma_u_offset, chroma_v_offset, buffer_name, buffer);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncMapBuffer(VADriverContextP context, VABufferID buffer_id, void **data_map)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestMapBuffer(context, buffer_id, data_map);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncPutImage(VADriverContextP context, VASurfaceID surface_id, VAImageID image, int src_x, int src_y, unsigned int src_width, unsigned int src_height, int dst_x, int dst_y, unsigned int dst_width, unsigned int dst_height)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestPutImage(context, surface_id, image, src_x, src_y, src_width, src_height, dst_x, dst_y, dst_width, dst_height);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncPutSurface(VADriverContextP context, VASurfaceID surface_id, void *draw, short src_x, short src_y, unsigned short src_width, unsigned short src_height, short dst_x, short dst_y, unsigned short dst_width, unsigned short dst_height, VARectangle *cliprects, unsigned int cliprects_count, unsigned int flags)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestPutSurface(context, surface_id, draw, src_x, src_y, src_width, src_height, dst_x, dst_y, dst_width, dst_height, cliprects, cliprects_count, flags);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncQueryConfigAttributes(VADriverContextP context, VAConfigID config_id, VAProfile *profile, VAEntrypoint *entrypoint, VAConfigAttrib *attributes, int *attributes_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestQueryConfigAttributes(context, config_id, profile, entrypoint, attributes, attributes_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncQueryConfigEntrypoints(VADriverContextP context, VAProfile profile, VAEntrypoint *entrypoints, int *entrypoints_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestQueryConfigEntrypoints(context, profile, entrypoints, entrypoints_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncQueryConfigProfiles(VADriverContextP context, VAProfile *profiles, int *profiles_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestQueryConfigProfiles(context, profiles, profiles_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncQueryDisplayAttributes(VADriverContextP context, VADisplayAttribute *attributes, int *attributes_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestQueryDisplayAttributes(context, attributes, attributes_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncQueryImageFormats(VADriverContextP context, VAImageFormat *formats, int *formats_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestQueryImageFormats(context, formats, formats_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncQuerySubpictureFormats(VADriverContextP context, VAImageFormat *formats, unsigned int *flags, unsigned int *formats_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestQuerySubpictureFormats(context, formats, flags, formats_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncQuerySurfaceAttributes(VADriverContextP context, VAConfigID config, VASurfaceAttrib *attributes, unsigned int *attributes_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestQuerySurfaceAttributes(context, config, attributes, attributes_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncQuerySurfaceStatus(VADriverContextP context, VASurfaceID surface_id, VASurfaceStatus *status)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestQuerySurfaceStatus(context, surface_id, status);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncReleaseBufferHandle(VADriverContextP context, VABufferID buffer_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestReleaseBufferHandle(context, buffer_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncRenderPicture(VADriverContextP context, VAContextID context_id, VABufferID *buffers, int buffers_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestRenderPicture(context, context_id, buffers, buffers_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncSetDisplayAttributes(VADriverContextP context, VADisplayAttribute *attributes, int attributes_count)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestSetDisplayAttributes(context, attributes, attributes_count);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncSetImagePalette(VADriverContextP context, VAImageID image_id, unsigned char *palette)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestSetImagePalette(context, image_id, palette);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncSetSubpictureChromakey(VADriverContextP context, VASubpictureID subpicture_id, unsigned int chromakey_min, unsigned int chromakey_max, unsigned int chromakey_mask)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestSetSubpictureChromakey(context, subpicture_id, chromakey_min, chromakey_max, chromakey_mask);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncSetSubpictureGlobalAlpha(VADriverContextP context, VASubpictureID subpicture_id, float global_alpha)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestSetSubpictureGlobalAlpha(context, subpicture_id, global_alpha);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncSetSubpictureImage(VADriverContextP context, VASubpictureID subpicture_id, VAImageID image_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestSetSubpictureImage(context, subpicture_id, image_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncSyncSurface(VADriverContextP context, VASurfaceID surface_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestSyncSurface(context, surface_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncUnlockSurface(VADriverContextP context, VASurfaceID surface_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestUnlockSurface(context, surface_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}

VAStatus SyncUnmapBuffer(VADriverContextP context, VABufferID buffer_id)
{
	struct request_data *driver_data = context->pDriverData;
	VAStatus sync_rc_;

	pthread_mutex_lock(&driver_data->lock);
	sync_rc_ = RequestUnmapBuffer(context, buffer_id);
	pthread_mutex_unlock(&driver_data->lock);

	return sync_rc_;
}
