#!/usr/bin/env python3
"""Generate src/sync.c and src/sync.h: one locking wrapper per VA entry point.

libva does not serialise driver calls, and clients decode each video on its own
thread, so every entry point has to take the driver lock before touching the
object heaps, the device handles or the queue state. Writing 49 wrappers by
hand invites one of them to be forgotten; generating them does not.

Run from the va-driver directory:  python3 tools/gen-sync.py
"""
import glob
import io
import os
import re

# A name a VA entry point will never use for a parameter.
LOCAL = "sync_rc_"

# vaTerminate frees driver_data, and with it the lock itself. A wrapper would
# unlock freed memory on the way out, so request.c wires vaTerminate straight
# to RequestTerminate. Generating a SyncTerminate nobody may call only leaves
# a trap for whoever wires the vtable next.
SKIP = {"RequestTerminate"}

HEADER_NOTE = """/*
 * Copyright (C) 2026 Orange Pi 5B image builders
 *
 * SPDX-License-Identifier: MIT
 *
 * GENERATED by tools/gen-sync.py -- do not edit by hand.
 */
"""


def split_params(params):
    out, depth, cur = [], 0, ""
    for ch in params:
        if ch == "(":
            depth += 1
        if ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def arg_name(decl):
    match = re.findall(r"(\w+)\s*$", decl.replace("[]", "").strip())
    return match[0] if match else None


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src = os.path.join(root, "src")

    protos = {}
    for header in sorted(glob.glob(os.path.join(src, "*.h"))):
        if os.path.basename(header) == "sync.h":
            continue
        text = io.open(header, encoding="utf-8").read()
        for m in re.finditer(r"^VAStatus\s+(Request\w+)\s*\(([^;]*?)\)\s*;",
                             text, re.M | re.S):
            if m.group(1) in SKIP:
                continue
            protos[m.group(1)] = " ".join(m.group(2).split())

    body = [HEADER_NOTE, '''
/*
 * RequestSyncSurface is the one that matters for throughput: it releases the
 * lock across the wait for the hardware, which is nearly all of a decode's
 * wall time. What is serialised here is bookkeeping, not decoding.
 */

#include <pthread.h>

#include <va/va_backend.h>

#include "buffer.h"
#include "config.h"
#include "context.h"
#include "image.h"
#include "picture.h"
#include "request.h"
#include "subpicture.h"
#include "surface.h"
#include "sync.h"
''']

    decls = [HEADER_NOTE, '''
#ifndef _SYNC_H_
#define _SYNC_H_

#include <va/va_backend.h>
''']

    for name in sorted(protos):
        params = protos[name]
        args = [arg_name(p) for p in split_params(params)]
        if None in args:
            raise SystemExit("cannot name the arguments of " + name)
        wrapper = name.replace("Request", "Sync", 1)
        body.append(
            "VAStatus %s(%s)\n"
            "{\n"
            "\tstruct request_data *driver_data = context->pDriverData;\n"
            "\tVAStatus %s;\n"
            "\n"
            "\tpthread_mutex_lock(&driver_data->lock);\n"
            "\t%s = %s(%s);\n"
            "\tpthread_mutex_unlock(&driver_data->lock);\n"
            "\n"
            "\treturn %s;\n"
            "}\n" % (wrapper, params, LOCAL, LOCAL, name, ", ".join(args), LOCAL))
        decls.append("VAStatus %s(%s);" % (wrapper, params))

    decls.append("\n#endif")

    io.open(os.path.join(src, "sync.c"), "w", encoding="utf-8").write("\n".join(body))
    io.open(os.path.join(src, "sync.h"), "w", encoding="utf-8").write("\n".join(decls))
    print("generated %d wrappers" % len(protos))


if __name__ == "__main__":
    main()
